extends: ["spectral:oas"]
rules:
  operation-description: true
  operation-operationId-unique: true
  openapi-tags: true
  path-declarations-must-exist: true
  path-keys-no-trailing-slash: true
  path-not-include-query: true